# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Pawpads' do
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
end
